### ISSUE TITLE
Update community links in README.md

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [dreemurrs-embedded/Pine64-Arch#371]
README.md currently has some broken or outdated links:

Matrix: #archmobile:kde.org
Telegram: @archlinux_pinephone

1. I was not able to find that Matrix channel on the kde.org Matrix server. Can you remove or update the Matrix info?
2. The Telegram channel looks like it's moved. Please update it to https://t.me/archmobile

**Comment by Danct12** [comment]
Matrix channel is hidden due to a recent homeserver raid, you can still join it by clicking the join button:

![Screenshot_20220409_063743](https://user-images.githubusercontent.com/19162768/162546753-2022b844-6e5b-441d-a381-efc64f80657e.png)

The Telegram channel is set to the moved one on purpose, this will not be changed.
