### ISSUE TITLE
location on maps

### ISSUE THREAD

**Issue by shulamy1** [dreemurrs-embedded/Pine64-Arch#446]
- Device: PinePhone
- Kernel Version : 5.19.3-1-danctnix (and older)
- UI: phosh

### Steps to reproduce
open maps and tap  "my location"

### Expected behavior
curser on my location

### Actual behavior
curser about 100km south from my location

**Comment by Ferenc-** [comment]
That is most likely because your location is not determined from your GNSS coordinates,
but by other means from Mozilla Location Services.
Check with [satellite](https://flathub.org/apps/details/page.codeberg.tpikonen.satellite), that you even have a GPS fix, and you have exact latitude and longitude values.

**Comment by shulamy1** [comment]
yes. you are right
now i have to find how to do it
ezik
